### ISSUE TITLE
why can't translate the full sentence?

### ISSUE THREAD

**Issue by mashagua** [Saravananslb/py-googletranslation#23]
i want to translate the sentence 
aa1="Do you want beneficial technologies being shaped by your ideas? Whether in the areas of mobility solutions, consumer goods, industrial technology or energy and building technology - with us,"
translator.translate(aa1, dest='zh-cn').text
but the result is only "你想要由你的想法塑造的有益技术吗？", only output the first sentences,is this api has the length limit?

**Comment by finia2NA** [comment]
Try using this branch: https://github.com/jonata/py-googletranslation
There's some issues with translating special characters that have been fixed there.
I had some Japanese sentences that were only partially translated with the main branch of this repo and work flawlessly with that branch.

**Comment by mashagua** [comment]
> 
> 
> Try using this branch: https://github.com/jonata/py-googletranslation
> There's some issues with translating special characters that have been fixed there.
> I had some Japanese sentences that were only partially translated with the main branch of this repo and work flawlessly with that branch.

I tried according to your suggestion,but there is an error:
Traceback (most recent call last):
  File "C:/Users/MSA2SGH/Desktop/interview_docx_xlsx/jd_related/google_trans.py", line 8, in <module>
    from pygoogletranslation import Translator
  File "C:\Users\MSA2SGH\AppData\Local\Programs\Python\Python36\lib\site-packages\pygoogletranslation\__init__.py", line 6, in <module>
    from pygoogletranslation.translate import Translator
  File "C:\Users\MSA2SGH\AppData\Local\Programs\Python\Python36\lib\site-packages\pygoogletranslation\translate.py", line 14, in <module>
    from pygoogletranslation import utils, urls
  File "C:\Users\MSA2SGH\AppData\Local\Programs\Python\Python36\lib\site-packages\pygoogletranslation\utils.py", line 8, in <module>
    from googletrans.models import TranslatedPart
ImportError: cannot import name 'TranslatedPart'
