### ISSUE TITLE
 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by jerry460** [Saravananslb/py-googletranslation#29]
Traceback (most recent call last):
  File "c:/Users/user/Downloads/free-google-translate-master/Python/1.py", line 5, in <module>
    translator.translate('Good Morning', dest='ta')
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\gtoken.py", line 194, in do       
    self._update()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\gtoken.py", line 62, in _update   
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
This is my trace back.
i want to know how can fix the problem

**Comment by shauryauppal** [comment]
Same issue I am also facing you found any fix?

**Comment by jerry460** [comment]
no,QAQ
